### ISSUE TITLE
ax650n板端编译报错

### ISSUE THREAD

**Issue by qin-yuhao** [AXERA-TECH/ax-pipeline#116]
In file included from /root/Desktop/ax-pipeline/examples/common/common_pipeline/ax650/common_pipeline_vo.cpp:30:
/root/Desktop/ax-pipeline/build/../bsp/msp/out/../sample/common/common_vo.h:130:5: error: ‘AX_VO_MODE_E’ does not name a type; did you mean ‘AX_VO_MODE_MAX’?
  130 |     AX_VO_MODE_E            enMode;
      |     ^~~~~~~~~~~~
      |     AX_VO_MODE_MAX
/root/Desktop/ax-pipeline/examples/common/common_pipeline/ax650/common_pipeline_vo.cpp: In function ‘AX_BOOL SetChnFrameRate(VO_CHN, VO_LAYER, VO_DEV, AX_U32)’:
/root/Desktop/ax-pipeline/examples/common/common_pipeline/ax650/common_pipeline_vo.cpp:296:56: error: could not convert ‘nFps’ from ‘AX_U32’ {aka ‘unsigned int’} to ‘AX_FRAME_RATE_CTRL_U’ {aka ‘_AX_FRAME_RATE_CTRL_U_’}
  296 |     AX_S32 ret = AX_VO_SetChnFrameRate(voLayer, voChn, nFps);
      |                                                        ^~~~
      |                                                        |
      |                                                        AX_U32 {aka unsigned int}
In file included from /root/Desktop/ax-pipeline/examples/common/common_pipeline/ax650/common_pipeline_vo.cpp:22:
/root/Desktop/ax-pipeline/examples/common/common_pipeline/ax650/common_pipeline_vo.cpp: In function ‘int _create_vo_hdmi(pipeline_t*)’:
/root/Desktop/ax-pipeline/examples/common/common_pipeline/./../../utilities/sample_log.h:34:21: warning: format ‘%d’ expects argument of type ‘int’, but argument 11 has type ‘std::vector<axVO_CHN_ATTR_T>::size_type’ {aka ‘long unsigned int’} [-Wformat=]
   34 | #define MACRO_GREEN "\033[1;30;32m"
      |                     ^
/root/Desktop/ax-pipeline/examples/common/common_pipeline/./../../utilities/sample_log.h:57:12: note: in expansion of macro ‘MACRO_GREEN’
   57 |     printf(MACRO_GREEN "[I][%32s][%4d]: " fmt MACRO_END "\n", __FUNCTION__, __LINE__, ##__VA_ARGS__)
      |            ^~~~~~~~~~~
/root/Desktop/ax-pipeline/examples/common/common_pipeline/ax650/common_pipeline_vo.cpp:428:13: note: in expansion of macro ‘ALOGI’
  428 |             ALOGI("layer %d: [(%d, %d) %dx%d], dispatch mode %d, layer depth %d, ChnNr %d, part mode %d, tolerance %d",
      |             ^~~~~
/root/Desktop/ax-pipeline/examples/common/common_pipeline/ax650/common_pipeline_vo.cpp:428:89: note: format string is defined here
  428 |             ALOGI("layer %d: [(%d, %d) %dx%d], dispatch mode %d, layer depth %d, ChnNr %d, part mode %d, tolerance %d",
      |                                                                                        ~^
      |                                                                                         |
      |                                                                                         int
      |                                                                                        %ld
make[2]: *** [examples/common/common_pipeline/CMakeFiles/common_pipeline.dir/build.make:146: examples/common/common_pipeline/CMakeFiles/common_pipeline.dir/ax650/common_pipeline_vo.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:520: examples/common/common_pipeline/CMakeFiles/common_pipeline.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by suilin1254703825** [comment]
你是[650编译](https://github.com/AXERA-TECH/ax-pipeline/blob/main/docs/compile_650.md )这里交叉编译错误了吗

**Comment by qin-yuhao** [comment]
> 你是[650编译](https://github.com/AXERA-TECH/ax-pipeline/blob/main/docs/compile_650.md)这里交叉编译错误了吗

不是，板端，好像是gcc太新的问题，应该用gcc-9
