### ISSUE TITLE
Need support AX630

### ISSUE THREAD

**Issue by szufafa** [AXERA-TECH/ax-pipeline#64]
need ax-pipeline/examples/libaxdl/src/ax_joint_runner_ax630.cpp

**Comment by ZHEQIUSHUI** [comment]
好像是一样的？

**Comment by ZHEQIUSHUI** [comment]
api好像跟620是一样的 我手上没630板子 没法开发哦

**Comment by szufafa** [comment]
感谢回复，大部分的API是相同的，但似乎在pipeline中的NUP调用AI_KIT方面不太相同，个人已经通过AX-test开发好了。

**Comment by BUG1989** [comment]
@szufafa 具体问题请在 AXERA QQ技术交流群里 小窗联系我
