### ISSUE TITLE
在开发板上编译报错

### ISSUE THREAD

**Issue by wnzsswzgwsdry** [AXERA-TECH/ax-pipeline#79]
ax-pipeline-main/examples/libaxdl/src/ax_common_api.cpp:9:10: fatal error: npu_cv_kit/         ax_npu_imgproc.h: No such file or directory
    9 | #include "npu_cv_kit/ax_npu_imgproc.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

在build文件夹内make -j4 也报错

**Comment by Czhazha** [comment]
我也在ax-pipeline编译报错
一开始是执行650的本地编译，cmake阶段报错，看了一下命令，改了-DCMAKE_TOOLCHAIN_FILE=../toolchains/aarch64-none-linux-gnu.toolchain.cmake为-DCMAKE_TOOLCHAIN_FILE=../toolchains/aarch64-linux-gnu.toolchain.cmake。
改过后cmake成功，然后make又报错
ax-pipeline/third-party/mp4demux/Mp4Demuxer.cpp:21:10: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type
不知道是哪里的问题，能帮忙解决下吗？

**Comment by ZHEQIUSHUI** [comment]
> 我也在ax-pipeline编译报错 一开始是执行650的本地编译，cmake阶段报错，看了一下命令，改了-DCMAKE_TOOLCHAIN_FILE=../toolchains/aarch64-none-linux-gnu.toolchain.cmake为-DCMAKE_TOOLCHAIN_FILE=../toolchains/aarch64-linux-gnu.toolchain.cmake。 改过后cmake成功，然后make又报错 ax-pipeline/third-party/mp4demux/Mp4Demuxer.cpp:21:10: error: ‘shared_ptr’ in namespace ‘std’ does not name a template type 不知道是哪里的问题，能帮忙解决下吗？

在`ax-pipeline/third-party/mp4demux/Mp4Demuxer.cpp` 添加 #include <memory>

暂不支持板端编译，建议交叉编译
